#!/usr/bin/env python3
"""

"""
##-- imports
from __future__ import annotations

import logging as logmod
import pathlib
import unittest
import warnings
from importlib.resources import files
from typing import (Any, Callable, ClassVar, Generic, Iterable, Iterator,
                    Mapping, Match, MutableMapping, Sequence, Tuple, TypeAlias,
                    TypeVar, cast)
from unittest import mock

from instal.validate.bridge_event_gen_validator import BridgeEventGenValidator
from instal.interfaces import ast as iAST
from instal.interfaces import validate
from instal.parser.v2.parser import InstalPyParser

##-- end imports

##-- warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    pass
##-- end warnings
logging = logmod.root
##-- data
data_path = files("instal.validate.__tests.__data")
##-- end data

parser = InstalPyParser()


class TestBridgeEventGenValidator(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        LOGLEVEL      = logmod.DEBUG
        LOG_FILE_NAME = "log.{}".format(pathlib.Path(__file__).stem)

        cls.file_h        = logmod.FileHandler(LOG_FILE_NAME, mode="w")
        cls.file_h.setLevel(LOGLEVEL)

        logging.setLevel(logmod.NOTSET)
        logging.addHandler(cls.file_h)


    @classmethod
    def tearDownClass(cls):
        logging.removeHandler(cls.file_h)

    def test_initial_ctor_with_validator(self):
        runner = validate.InstalValidatorRunner([ BridgeEventGenValidator() ])
        self.assertIsInstance(runner, validate.InstalValidatorRunner)
        self.assertIsNotNone(runner.validators)

    def test_basic_pass(self):
        """
        Validator no reports are generated by default
        """
        file_name = data_path / "bridge_structure_basic.iab"
        runner    = validate.InstalValidatorRunner([ BridgeEventGenValidator() ])

        data = parser.parse_bridge(file_name)
        self.assertIsInstance(data[0], iAST.InstitutionDefAST)

        result = runner.validate(data)
        self.assertFalse(result)

    def test_basic_with_rules_fail(self):
        """
        Validator no reports are generated by default
        """
        file_name_bridge = data_path / "bridge_event_gen_rules.iab"
        file_name_insts  = data_path / "bridge_basic_sourceSinks.ial"
        runner           = validate.InstalValidatorRunner([ BridgeEventGenValidator() ])

        bridge_data      = parser.parse_bridge(file_name_bridge)
        inst_data        = parser.parse_institution(file_name_insts)

        self.assertIsInstance(bridge_data[0], iAST.BridgeDefAST)
        self.assertIsInstance(inst_data[0], iAST.InstitutionDefAST)

        with self.assertRaises(Exception) as cm:
            runner.validate(bridge_data + inst_data)

        the_exc = cm.exception
        results = the_exc.args[1]
        self.assertTrue(results)
        self.assertIn(logmod.ERROR, results)
        self.assertEqual(len(results[logmod.ERROR]), 2)

    def test_basic_with_rules_pass(self):
        """
        Validator no reports are generated by default
        """
        bridge_file_name = data_path / "bridge_event_gen_rules.iab"
        inst_file_name   = data_path / "bridge_event_gen_insts.ial"
        runner    = validate.InstalValidatorRunner([ BridgeEventGenValidator() ])

        bridge_data = parser.parse_bridge(bridge_file_name)
        inst_data   = parser.parse_institution(inst_file_name)

        self.assertIsInstance(bridge_data[0], iAST.BridgeDefAST)
        self.assertTrue(inst_data)

        results = runner.validate(bridge_data + inst_data)

        self.assertFalse(results)



##-- ifmain
if __name__ == '__main__':
    unittest.main()

##-- end ifmain
